/**
 * Package Builder
 *
 * Builds exportable test packages with proper project structure.
 */

import type { TalosApplication, TalosTest } from "../types.js";
import type { TalosRepository } from "../repository.js";
import type { ExportConfig } from "../config.js";
import { CredentialSanitizer, type SanitizationResult } from "./credential-sanitizer.js";

// ── Types ─────────────────────────────────────────────────────────────────────

export type PackageBuilderOptions = {
  config: ExportConfig;
  repository: TalosRepository;
};

export type PackageTemplate = "playwright" | "minimal" | "full";

export type PackageContents = {
  files: PackageFile[];
  totalSize: number;
  testCount: number;
};

export type PackageFile = {
  path: string;
  content: string;
  type: "test" | "config" | "fixture" | "page-object" | "utility" | "doc";
};

export type BuildOptions = {
  template?: PackageTemplate;
  includePageObjects?: boolean;
  includeFixtures?: boolean;
  sanitizeCredentials?: boolean;
  generateReadme?: boolean;
  generateEnvTemplate?: boolean;
};

// ── Templates ─────────────────────────────────────────────────────────────────

const PLAYWRIGHT_CONFIG_TEMPLATE = `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: process.env.BASE_URL || '{{BASE_URL}}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
`;

const PACKAGE_JSON_TEMPLATE = `{
  "name": "{{NAME}}-tests",
  "version": "1.0.0",
  "description": "E2E tests for {{NAME}} - exported from Talos",
  "scripts": {
    "test": "playwright test",
    "test:headed": "playwright test --headed",
    "test:ui": "playwright test --ui",
    "test:debug": "playwright test --debug",
    "report": "playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.40.0",
    "typescript": "^5.3.0"
  }
}
`;

const README_TEMPLATE = `# {{NAME}} - End-to-End Tests

This test suite was exported from Talos on {{DATE}}.

## Setup

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Install Playwright browsers:
   \`\`\`bash
   npx playwright install
   \`\`\`

3. Configure environment variables:
   - Copy \`.env.example\` to \`.env\`
   - Fill in the required values

## Running Tests

\`\`\`bash
# Run all tests
npm test

# Run in headed mode
npm run test:headed

# Run with UI
npm run test:ui

# Debug mode
npm run test:debug
\`\`\`

## Test Structure

\`\`\`
tests/
{{TEST_STRUCTURE}}
\`\`\`

## Tests Included

{{TEST_LIST}}

---
*Generated by Talos Test Automation System*
`;

const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist"
  },
  "include": ["tests/**/*", "playwright.config.ts"]
}
`;

// ── Package Builder ───────────────────────────────────────────────────────────

export class PackageBuilder {
  private repository: TalosRepository;
  private sanitizer: CredentialSanitizer;

  constructor(options: PackageBuilderOptions) {
    void options.config; // Placeholder for future use
    this.repository = options.repository;
    this.sanitizer = new CredentialSanitizer();
  }

  /**
   * Build a complete test package for an application.
   */
  build(applicationId: string, options: BuildOptions = {}): PackageContents {
    const app = this.repository.getApplication(applicationId);
    if (!app) {
      throw new Error(`Application not found: ${applicationId}`);
    }

    const tests = this.repository.getTestsByApplication(applicationId);
    const template = options.template ?? "playwright";
    const files: PackageFile[] = [];
    const envReplacements: SanitizationResult["replacements"] = [];

    // Add config files based on template
    files.push(...this.buildConfigFiles(app, template));

    // Add test files
    for (const test of tests) {
      const testFile = this.buildTestFile(test, options);
      files.push(testFile.file);
      
      if (options.sanitizeCredentials !== false) {
        envReplacements.push(...testFile.replacements);
      }
    }

    // Add fixtures if requested
    if (options.includeFixtures) {
      files.push(this.buildFixtureFile(app));
    }

    // Add page objects if requested
    if (options.includePageObjects) {
      const pageObjects = this.buildPageObjects(app, tests);
      files.push(...pageObjects);
    }

    // Add README if requested
    if (options.generateReadme !== false) {
      files.push(this.buildReadme(app, tests));
    }

    // Add env template if requested
    if (options.generateEnvTemplate !== false && envReplacements.length > 0) {
      const envTemplate = this.sanitizer.generateEnvTemplate(envReplacements);
      files.push({
        path: ".env.example",
        content: envTemplate,
        type: "doc",
      });
    }

    const totalSize = files.reduce((sum, f) => sum + f.content.length, 0);

    return {
      files,
      totalSize,
      testCount: tests.length,
    };
  }

  /**
   * Build configuration files.
   */
  private buildConfigFiles(app: TalosApplication, _template: PackageTemplate): PackageFile[] {
    const files: PackageFile[] = [];

    // playwright.config.ts
    const playwrightConfig = PLAYWRIGHT_CONFIG_TEMPLATE.replace(
      "{{BASE_URL}}",
      app.baseUrl ?? "http://localhost:3000"
    );
    files.push({
      path: "playwright.config.ts",
      content: playwrightConfig,
      type: "config",
    });

    // package.json
    const packageJson = PACKAGE_JSON_TEMPLATE
      .replace(/\{\{NAME\}\}/g, this.slugify(app.name));
    files.push({
      path: "package.json",
      content: packageJson,
      type: "config",
    });

    // tsconfig.json
    files.push({
      path: "tsconfig.json",
      content: TSCONFIG_TEMPLATE,
      type: "config",
    });

    // .gitignore
    files.push({
      path: ".gitignore",
      content: `node_modules/
test-results/
playwright-report/
.env
*.log
`,
      type: "config",
    });

    return files;
  }

  /**
   * Build a test file.
   */
  private buildTestFile(
    test: TalosTest,
    options: BuildOptions
  ): { file: PackageFile; replacements: SanitizationResult["replacements"] } {
    let code = test.code;
    let replacements: SanitizationResult["replacements"] = [];

    // Sanitize credentials if enabled
    if (options.sanitizeCredentials !== false) {
      const result = this.sanitizer.sanitize(code);
      code = result.sanitizedCode;
      replacements = result.replacements;
    }

    // Wrap in proper test structure if needed
    if (!code.includes("test(") && !code.includes("test.describe(")) {
      code = this.wrapInTestStructure(test.name, code);
    }

    // Ensure imports are present
    if (!code.includes("import {") && !code.includes("import type")) {
      code = `import { test, expect } from '@playwright/test';\n\n${code}`;
    }

    const fileName = this.slugify(test.name) + ".spec.ts";

    return {
      file: {
        path: `tests/${fileName}`,
        content: code,
        type: "test",
      },
      replacements,
    };
  }

  /**
   * Wrap code in a proper Playwright test structure.
   */
  private wrapInTestStructure(testName: string, code: string): string {
    return `import { test, expect } from '@playwright/test';

test('${testName}', async ({ page }) => {
${code.split("\n").map(line => `  ${line}`).join("\n")}
});
`;
  }

  /**
   * Build a fixture file.
   */
  private buildFixtureFile(app: TalosApplication): PackageFile {
    const content = `import { test as base } from '@playwright/test';

// Custom fixtures for ${app.name}

export type CustomFixtures = {
  authenticatedPage: ReturnType<typeof import('@playwright/test').Page['prototype']['goto']>;
};

export const test = base.extend<CustomFixtures>({
  authenticatedPage: async ({ page }, use) => {
    // Add authentication logic here
    // Example: await page.goto('/login');
    // await page.fill('[name="email"]', process.env.TEST_EMAIL);
    // await page.fill('[name="password"]', process.env.TEST_PASSWORD);
    // await page.click('button[type="submit"]');
    
    await use(page.goto.bind(page));
  },
});

export { expect } from '@playwright/test';
`;

    return {
      path: "tests/fixtures.ts",
      content,
      type: "fixture",
    };
  }

  /**
   * Build page object files.
   */
  private buildPageObjects(
    _app: TalosApplication,
    tests: TalosTest[]
  ): PackageFile[] {
    const files: PackageFile[] = [];

    // Analyze tests to extract potential page objects
    const pages = this.analyzeTestsForPages(tests);

    for (const [pageName, selectors] of pages) {
      const content = this.buildPageObjectClass(pageName, selectors);
      files.push({
        path: `tests/pages/${this.slugify(pageName)}.page.ts`,
        content,
        type: "page-object",
      });
    }

    // Add base page class
    files.push({
      path: "tests/pages/base.page.ts",
      content: `import { Page } from '@playwright/test';

export class BasePage {
  constructor(protected page: Page) {}

  async navigate(path: string) {
    await this.page.goto(path);
  }

  async getTitle() {
    return this.page.title();
  }
}
`,
      type: "page-object",
    });

    return files;
  }

  /**
   * Analyze tests to extract page information.
   */
  private analyzeTestsForPages(tests: TalosTest[]): Map<string, string[]> {
    const pages = new Map<string, string[]>();

    for (const test of tests) {
      // Look for goto calls to identify pages
      const gotoMatches = test.code.matchAll(/page\.goto\(['"]([^'"]+)['"]\)/g);
      for (const match of gotoMatches) {
        const url = match[1];
        const pageName = this.urlToPageName(url);
        
        if (!pages.has(pageName)) {
          pages.set(pageName, []);
        }
      }

      // Look for selectors in the test
      const selectorMatches = test.code.matchAll(/(?:locator|getBy\w+)\(['"]([^'"]+)['"]\)/g);
      // Iterate through matches (simplified - real implementation would associate selectors with pages)
      Array.from(selectorMatches);
    }

    return pages;
  }

  /**
   * Build a page object class.
   */
  private buildPageObjectClass(pageName: string, _selectors: string[]): string {
    const className = this.toPascalCase(pageName) + "Page";
    
    return `import { Page, Locator } from '@playwright/test';
import { BasePage } from './base.page';

export class ${className} extends BasePage {
  // Locators
  // Add your locators here
  
  constructor(page: Page) {
    super(page);
  }

  // Actions
  async open() {
    await this.navigate('/${this.slugify(pageName)}');
  }
}
`;
  }

  /**
   * Build README file.
   */
  private buildReadme(app: TalosApplication, tests: TalosTest[]): PackageFile {
    const testStructure = tests
      .map(t => `├── ${this.slugify(t.name)}.spec.ts`)
      .join("\n");

    const testList = tests
      .map(t => `- **${t.name}**: ${(t.metadata as Record<string, string>)?.generatedFrom ?? "N/A"}`)
      .join("\n");

    const content = README_TEMPLATE
      .replace(/\{\{NAME\}\}/g, app.name)
      .replace("{{DATE}}", new Date().toISOString().split("T")[0])
      .replace("{{TEST_STRUCTURE}}", testStructure)
      .replace("{{TEST_LIST}}", testList);

    return {
      path: "README.md",
      content,
      type: "doc",
    };
  }

  /**
   * Convert URL to page name.
   */
  private urlToPageName(url: string): string {
    const path = url.replace(/^https?:\/\/[^/]+/, "").replace(/^\//, "");
    if (!path || path === "/") return "home";
    return path.split("/")[0].replace(/[^a-zA-Z0-9]/g, "-");
  }

  /**
   * Convert string to slug.
   */
  private slugify(str: string): string {
    return str
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  }

  /**
   * Convert string to PascalCase.
   */
  private toPascalCase(str: string): string {
    return str
      .split(/[-_\s]+/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join("");
  }
}
