/**
 * Test Data Seeder (#480)
 *
 * Generates test data seeding hooks for generated tests:
 * - beforeAll database seeding via API calls or SQL
 * - afterAll cleanup
 * - Fixture files with parameterization
 */

import type {
  TestDataSeedConfig,
  TestDataSeedResult,
  SeedStrategyType,
} from "../types.js";

// ── Types ─────────────────────────────────────────────────────────────────────

export type DataSeederOptions = {
  /** Default seed strategy */
  defaultStrategy?: SeedStrategyType;
  /** API base URL for API-based seeding */
  apiBaseUrl?: string;
};

export type SeedHooks = {
  beforeAllCode: string;
  afterAllCode: string;
  fixtureImports: string[];
};

export type FixtureDefinition = {
  name: string;
  data: Record<string, unknown>[];
  parameters: Record<string, string>;
};

// ── Data Seeder ───────────────────────────────────────────────────────────────

export class DataSeeder {
  private defaultStrategy: SeedStrategyType;
  private apiBaseUrl: string | undefined;

  constructor(options?: DataSeederOptions) {
    this.defaultStrategy = options?.defaultStrategy ?? "api";
    this.apiBaseUrl = options?.apiBaseUrl;
  }

  /**
   * Generate seed hooks code for test files.
   */
  generateSeedHooks(config: TestDataSeedConfig): SeedHooks {
    switch (config.strategy) {
      case "api":
        return this.generateApiHooks(config);
      case "sql":
        return this.generateSqlHooks(config);
      case "fixture":
        return this.generateFixtureHooks(config);
      default:
        return this.generateApiHooks(config);
    }
  }

  /**
   * Generate fixture file content.
   */
  generateFixtureFile(fixture: FixtureDefinition): string {
    const lines: string[] = [];

    lines.push(`/**`);
    lines.push(` * Test fixture: ${fixture.name}`);
    lines.push(` * Auto-generated by Talos Data Seeder`);
    lines.push(` */`);
    lines.push("");
    lines.push(`export const ${this.toCamelCase(fixture.name)}Fixture = {`);
    lines.push(`  name: '${fixture.name}',`);

    // Parameters
    if (Object.keys(fixture.parameters).length > 0) {
      lines.push(`  parameters: {`);
      for (const [key, value] of Object.entries(fixture.parameters)) {
        lines.push(`    ${key}: '${this.escapeString(value)}',`);
      }
      lines.push(`  },`);
    }

    // Data records
    lines.push(`  data: ${JSON.stringify(fixture.data, null, 4)},`);
    lines.push(`} as const;`);

    return lines.join("\n");
  }

  /**
   * Build a seed config from user parameters.
   */
  buildSeedConfig(
    strategy?: SeedStrategyType,
    setupScript?: string,
    cleanupScript?: string,
    fixtures?: Record<string, unknown>[],
    parameters?: Record<string, string>
  ): TestDataSeedConfig {
    return {
      strategy: strategy ?? this.defaultStrategy,
      setupScript: setupScript ?? "",
      cleanupScript: cleanupScript ?? "",
      fixtures,
      parameters,
    };
  }

  /**
   * Execute a seed config (returns result summary).
   */
  async executeSeed(config: TestDataSeedConfig): Promise<TestDataSeedResult> {
    const startTime = Date.now();

    try {
      const recordsCreated = config.fixtures?.length ?? 0;

      return {
        success: true,
        strategy: config.strategy,
        recordsCreated,
        durationMs: Date.now() - startTime,
      };
    } catch (err) {
      return {
        success: false,
        strategy: config.strategy,
        recordsCreated: 0,
        error: err instanceof Error ? err.message : String(err),
        durationMs: Date.now() - startTime,
      };
    }
  }

  // ── Private Generators ──────────────────────────────────────────────────────

  private generateApiHooks(config: TestDataSeedConfig): SeedHooks {
    const baseUrl = this.apiBaseUrl ?? "http://localhost:3000";

    const beforeAllCode = [
      `test.beforeAll(async () => {`,
      `  // Seed test data via API`,
      `  const baseUrl = '${this.escapeString(baseUrl)}';`,
    ];

    if (config.setupScript) {
      beforeAllCode.push(`  ${config.setupScript}`);
    } else if (config.fixtures && config.fixtures.length > 0) {
      beforeAllCode.push(`  for (const record of testFixtures) {`);
      beforeAllCode.push(`    await fetch(\`\${baseUrl}/api/seed\`, {`);
      beforeAllCode.push(`      method: 'POST',`);
      beforeAllCode.push(`      headers: { 'Content-Type': 'application/json' },`);
      beforeAllCode.push(`      body: JSON.stringify(record),`);
      beforeAllCode.push(`    });`);
      beforeAllCode.push(`  }`);
    }

    beforeAllCode.push(`});`);

    const afterAllCode = [
      `test.afterAll(async () => {`,
      `  // Clean up test data`,
    ];

    if (config.cleanupScript) {
      afterAllCode.push(`  ${config.cleanupScript}`);
    } else {
      afterAllCode.push(`  await fetch('${this.escapeString(baseUrl)}/api/seed/cleanup', { method: 'DELETE' });`);
    }

    afterAllCode.push(`});`);

    return {
      beforeAllCode: beforeAllCode.join("\n"),
      afterAllCode: afterAllCode.join("\n"),
      fixtureImports: config.fixtures ? [`const testFixtures = ${JSON.stringify(config.fixtures, null, 2)};`] : [],
    };
  }

  private generateSqlHooks(config: TestDataSeedConfig): SeedHooks {
    const beforeAllCode = [
      `test.beforeAll(async () => {`,
      `  // Seed test data via SQL`,
      config.setupScript ? `  ${config.setupScript}` : `  // Add SQL seed queries here`,
      `});`,
    ].join("\n");

    const afterAllCode = [
      `test.afterAll(async () => {`,
      `  // Clean up test data`,
      config.cleanupScript ? `  ${config.cleanupScript}` : `  // Add SQL cleanup queries here`,
      `});`,
    ].join("\n");

    return {
      beforeAllCode,
      afterAllCode,
      fixtureImports: [],
    };
  }

  private generateFixtureHooks(config: TestDataSeedConfig): SeedHooks {
    const beforeAllCode = [
      `test.beforeAll(async () => {`,
      `  // Load and apply fixture data`,
      config.setupScript ? `  ${config.setupScript}` : `  // Apply fixtures from imported file`,
      `});`,
    ].join("\n");

    const afterAllCode = [
      `test.afterAll(async () => {`,
      config.cleanupScript ? `  ${config.cleanupScript}` : `  // Fixture cleanup`,
      `});`,
    ].join("\n");

    return {
      beforeAllCode,
      afterAllCode,
      fixtureImports: [`import { fixtures } from './fixtures';`],
    };
  }

  private toCamelCase(s: string): string {
    return s
      .replace(/[^a-zA-Z0-9]/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()))
      .join("");
  }

  private escapeString(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  }
}
